name: ikla_mobile
version: 1.0.0+1
publish_to: none
description: A Mobile Magazine named Ikla
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  google_sign_in: ^4.5.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: eUkraine
      fonts:
        - asset: assets/fonts/eUkraine/e-Ukraine-Bold.ttf
        - asset: assets/fonts/eUkraine/e-Ukraine-Light.ttf
        - asset: assets/fonts/eUkraine/e-Ukraine-Regular.ttf
    - family: eUkraineHead
      fonts:
        - asset: assets/fonts/eUkraine/e-UkraineHead-Bold.ttf
    - family: KyivType
      fonts:
        - asset: assets/fonts/KyivType/KyivTypeTitling-Heavy3.ttf
